version: '3'

services:
  perros:
    build: ./perros-service

  premios:
    build: ./premios-service

  razas:
    build: ./razas-service

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - perros
      - premios
      - razas